# This manifest describes two applications where nginx-app can communicate with redis-app
apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: nginx-app
spec:
  image: nginx
  port: 8080
  accessPolicy:
    outbound:
      rules:
        - application: redis-app
---
apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: redis-app
spec:
  image: redis
  port: 6379
  accessPolicy:
    inbound:
      rules:
        - application: nginx-app